TakwimuAfrica/Takwimu

takwimu/templates/takwimu/_includes/header/profile.html

This fixes icons that have blank square. Before font-awesome icons were appended by fas `e.g. fas fa-icon` which is solid style in Font Awesome 5. The fix was mostly done in `django-fontawesome` package where icons are now appended by either `fas`, `fab`, or `far` depending on its stated style in `icons.yml`. Changes in this PR accommodate the new icon drop down value which is used to display icon in topic buttons div.
Run `pip install -r requirements.txt` to get recent changes on `django-fontawesome`
Fixes #137

fixed icons with different style

---

takwimu/static/css/takwimu.scss
takwimu/templates/profile/profile_detail.html
takwimu/templates/profile/profile_detail_census.html
takwimu/templates/profile/profile_detail_takwimu.html
takwimu/urls.py

Override the HURUmap profile/profile_detail.html template to use a Takwimu base template.
Focus should be on the navbar, footer and the general look and feel to match Takwimu
Fixes #194

[HURUmap] Override profile detail template

---

takwimu/templates/takwimu/_includes/navbar/_index.html

Showing Find data by country page when clicking **Country Profiles** navbar menu item.

Showing data by country on Country Profiles click

---

takwimu/templates/homepage.html
takwimu/templates/profile/profile_detail.html
takwimu/templates/takwimu/_includes/profile/country_section.html

Added a section on hurumap country profile page with a button that can direct user to country analysis. I added a new layout `country-section` to be included in country profile landing page, and profile detail landing page
Fixes #252
**Profile Details Page with `country-section` layout after data viz**
**Profile Laniding Page with `country-section` layout after map**

add a country map section in profile details that directs to analysis

---

takwimu/templates/takwimu/_includes/navbar/support_services.html

Set "Community Forum" link to `SupportSetting.community` url.
Fixes #273

Fixes "Link to community forum broken"

---

takwimu/templates/profile/profile_detail.html

`country map` section on Profile detail view for geography levels below country now directs user to their specific parent country analysis fixing the existing bug on develop branch which directs user to level analysis (does not exist)
Fixes #297

Fix: Country analysis section for sub-national level profile view

---

takwimu/templates/takwimu/_includes/profile/topic_detail.html

This PR fixes the topic anchor navigation bug. It changes the anchor target to the div tag that contain the entire data topic, and not a sub-child tag element as it was before. Also adjusted the y-padding for topic data as per design `topic details sections from the deign has a top spacing that matches the height of the fixed nav-bar` 
Fixes #188

fix anchor navigation

---

takwimu/sql/causes_of_death_over_five.sql
takwimu/sql/causes_of_death_under_five.sql
takwimu/sql/health_centers.sql
takwimu/sql/health_centers_ownership.sql
takwimu/sql/health_workers.sql
takwimu/sql/hiv_health_centers.sql
takwimu/sql/inpatient_diagnosis_over_five.sql
takwimu/sql/inpatient_diagnosis_under_five.sql
takwimu/sql/outpatient_diagnosis_over_five.sql
takwimu/sql/outpatient_diagnosis_under_five.sql
takwimu/templates/profile/profile_detail.html

Some SQL files did not have `DROP` statements before `CREATE TABLE` statements causing errors/warning when executed.

Add missing drop statements to SQL files

---

takwimu/settings.py
takwimu/templates/profile/profile_detail.html

Takwimu had not set it's own tagline and description and hence the default HURUmap/Wazimap values were used.
Fixes #341 

Overide HURUmap tagline and description.

---

takwimu/sql/wazimap_geography.sql

Dump was created from PG 10 which uses the optional clause `AS <data_type>` in the `CREATE SEQUENCE` that is not supported in PG 9.5 (used by `docker-compose`) causing sql migration errors.

Remove SQL features incompatible with PG 9.5

---

requirements.txt

`pip` doesn't process `dependency_links` in `setup.py` by default. One needs to pass `--process-dependency-links` as part of `pip install` arguments. However, this has also been deprecated, see: [this issue](https://github.com/pypa/pip/issues/4187)
Hence the need to add a direct link to @OpenUpSA/wazimap in `requrements.txt`

Force pip to install wazimap from Github

---

takwimu/templates/takwimu/_includes/dataview/hurumap.html
takwimu/templatetags/datastructuretags.py

Since there could be more than one HURUmap Widget on a page, use UUID to
ensure each widget has a unique id.

Give each HURUmap Widget unique id

---

takwimu/models/dashboard.py
takwimu/templates/takwimu/_includes/dataview/hurumap.html

HURUmap Widget couldn't display sources as well as any description on the viz.

Add subtitle and fix source on HURUmap Widget

---

takwimu/templates/takwimu/_includes/dataview/hurumap.html

HURUmap widgets couldn't be shown on the same page because the script wanted to process all of them at the same time.This only works on those cases where some are not hidden as in hidden tabs.
This is fixed by making the script capable of process a single iframe at a time as well as adding listeners for when inactive tabs on widgets and indicators are activated.
Fixes #403 

Fix multiple HURUmap widgets on a single page

---

.travis.yml

From https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657:
Yeah so this happens because of the /etc/boto.cfg file which (I believe) Google adds to their system images - the idea being that it loads some plugins that let you use boto more easily with Google Cloud services. This is mostly useless in a CI environment though. If you look at the config file, you'll see that it tries to load a Python plugin, which the travis people must have somehow corrupted in this image. It is unfortunate that they switched to a new image without testing widely used libraries like `boto`.

[Hotfix] Ignore any found boto.cfg file

---

.travis.yml

From https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657:
Yeah so this happens because of the /etc/boto.cfg file which (I believe) Google adds to their system images - the idea being that it loads some plugins that let you use boto more easily with Google Cloud services. This is mostly useless in a CI environment though. If you look at the config file, you'll see that it tries to load a Python plugin, which the travis people must have somehow corrupted in this image. It is unfortunate that they switched to a new image without testing widely used libraries like `boto`.

[Hotfix] Remove /etc/boto.cfg file

---

.travis.yml
requirements.txt

`urllib3` released `v1.24` yesterday which breaks `requests` causing deployment failures.
See:
+ https://github.com/urllib3/urllib3/issues/1459
+ https://github.com/requests/requests/issues/4830        
Solution: Pin `urllib3`  to `v1.23` until resolved upstream

Bandage for Requests/Urllib3 incompatiblity

---

docker-compose.yml
docker-entrypoint.sh
takwimu/settings.py

To reduce the DevOps work of managing yet another instance, we will start with database caching for now while Takwimu still has low volume. Should the need arise in the future, the topic of which caching is best for Takwimu will discussed again.

[Feature] Use database caching instead of Redis

---

takwimu/search/takwimu_search.py
takwimu/templates/takwimu/_includes/search/sidebar.html
takwimu/views.py

Current search implementation fails when filters contain spaces or dash which limits the ability to drill down on search results. This PR improves the ability to handle search filters as well as index country and category/topic names in addition to content.

[SEARCH] Improve search query optimization

---

takwimu/templates/takwimu/_includes/sections/explore/topics.html

`slugify` actually removed `/` path separators.

Fix country flag issue

---

takwimu/management/commands/update_topics_index.py
takwimu/search/takwimu_search.py
takwimu/search/utils.py
takwimu/settings.py
takwimu/signals.py
takwimu/templates/takwimu/_includes/search/table.html

Concatenating everything into a single field does not work well for cases where different fields should carry different weight. For example:
1. kenya medical: Here, results from Kenya with medical (or similar terms) should be prioritised over results from other countries even if those other countries have exact medical matching indicators.
2. policy gender: Since there are policy specific categories, indicators matching gender should be prioritised over other categories.
The key issue here is adding multi field search with tunable weights (in settings.py) with good enough defaults.
New search on the right shows how emphasis can be given to country, and title over body content.

162008192 Multi Field Search Support

---

takwimu/templates/takwimu/_layouts/_base.html

From [v4.1.2](https://github.com/twbs/bootstrap/issues/26423), bootstrap has changed the way it internally get DOM elements; from using jQuery to using HTML5 native methods. This breaks the `collapse plugin` which is used by ALL indicator tabs on the site see: https://github.com/twbs/bootstrap/issues/26968.

Downgrade bootstrap to v4.1.1 [162216054]

---

takwimu/templates/takwimu/_includes/dataview/hurumap.html

+ Use dimensions set in embed widget details instead of trying to calculate them,
+ Simplify the embed function to work with just one frame and remove unnecessary auto resize methods, and
+ Simplify load event handler to handle all 3 cases.

Fix Embedded HURUmap Widget White Space Issues [#162261247]

---

takwimu/static/css/takwimu.scss
takwimu/templates/takwimu/_includes/footer.html
takwimu/templates/takwimu/_includes/navbar/about.html

Fix partners logos on Navbar about dropdown and footer. This should hold until UX migration.

Fix Partners Logos [161713150]

---

takwimu/templates/takwimu/profile_page.html

Events were being sent using secondary trackers instead of the default Takwimu tracker.

Use default tracker to send selection/copy events [Hotfix]

---

requirements.txt

Use [CodeForAfricaLabs/Wazimap](https://github.com/CodeForAfricaLabs/Wazimap/releases) & [CodeForAfrica/HURUmap](https://github.com/CodeForAfrica/HURUmap/releases)  releases instead of `master` branch

Use Wazimap/HURUmap releases [Hotfix]

---

takwimu/management/commands/update_topics_index.py
takwimu/search/takwimu_search.py
takwimu/search/utils.py
takwimu/settings.py

Index indicator and widget metadata separately and add them as part of searchable content. For now, only widget's `label` and `source` are considered as metadata.

Index indicator/widget metadata [163319354]

---

takwimu/context_processors.py
takwimu/models/dashboard.py
takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
takwimu/templates/takwimu/home_page.html
takwimu/utils/helpers.py
takwimu/utils/medium.py

Load Medium posts from URL provided in `SocialMediaSettings` rather than hard-coded `takwimu-africa`. Also:
i. Load articles via API rather than templates, and
ii. Enable loading articles from `staging.takwimu.africa`.

Load Medium posts from URL provided in SocialMediaSettings

---

takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
takwimu/takwimu_ui/src/components/Navigation/DropDownButton.js

Presence of `alt` text on dropdown buttons causes nav components to **jump** when first opened.
Also: `classNames` was not imported in `OtherInfoNav` causing runtime error when visiting any page using it.

[Staging] Fix Nav Dropdown

---

takwimu/static/js/charts.js
takwimu/takwimu_ui/src/components/DataContainer/FeaturedDataContainer.js

1. `v0.8` assumes `window.takwimu.country` will be defined in `charts.js`. This is not the case for all pages except the analysis pages,
2. `v0.8` implementation of download doesn't take into consideration that the chart is in an `iframe`. FF will not allow clicking of the auto-generated `a` _unless_ it's added to the `body` first.
Fixes # 165934876

[Staging] Fix featured data

---

takwimu/takwimu_ui/src/components/ContentNavigation.js
takwimu/takwimu_ui/src/components/Navigation/index.js
takwimu/takwimu_ui/src/components/Next/Card.js

[Staging] Feedback 03

---

takwimu/templates/data/_base_data.html
takwimu/urls.py

The `compare` action on Data by topics charts renders 404. Here's a fix that adds a url and override data template to match design

[Staging] Fix Chart Compare Action 

---

takwimu/takwimu_ui/public/index.html
takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
takwimu/takwimu_ui/src/components/Next/Home.js

[Staging] Fix component links

---

takwimu/management/commands/update_topics_index.py
takwimu/search/takwimu_search.py

`update_topics_index` was failing for analysis data as some `profilesectionpage` had empty titles while es match titles. This bug is fixed by setting title to a random string `null` when it's empty.

[Staging] Fix search index

---

takwimu/management/commands/update_topics_index.py

Deleting ProfileDate before indexing means we'll be losing any summaries that have been written by content team. This is not acceptable.
N/A

[Staging] [Hotfix] Preserve ProfileData

---

takwimu/renderers.py
takwimu/urls.py
takwimu/views.py

Some flourish viz have assets folders e.g. css/style.css. 
Fix our assumption that everything will be served from widget zip file root.

[FIX] Flourish widget assets folder support

---

takwimu/views.py

Flourish style-sheet, `style.css` and `choices/styles/css/choices.min.css` fail to load and render 500. This PR fixes this bug which was due to a semantic error in reconstructing flourish path.

[Bug] Fix Flourish Stylesheet

---

takwimu/takwimu_ui/src/components/AnalysisContent/index.js
takwimu/takwimu_ui/src/components/TableOfContent.js
takwimu/takwimu_ui/src/pages/Analysis.js

The `aside` component used for in page navigation in Content (**Country Analysis**, **About** and **Contact**) pages cuts of content when browser window's height is less than it's height.
This PR address this as well as enable scrolling of the `aside` content when the Content page footer comes into view.

Fix content page aside overflow and scroll

---

takwimu/takwimu_ui/src/components/AnalysisContent/Actions/DownloadPDF.js
takwimu/takwimu_ui/src/components/AnalysisContent/index.js

On initial Carousel topic load, we currently try to load and render PDF for download without making sure that we actually have data i.e. data is not empty. This PR:

Fix Carousel topic load error

---

takwimu/static/js/charts.js
takwimu/templates/settings_js.html

`Chart.js` has hard-coded paths to static files e.g. `/static/img/network-connections.svg`, which **404** in production due to the use of `S3`. This PR fixes that by:
N/A

Fix static path reference in JavaScript files

---

takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js
takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
takwimu/takwimu_ui/src/index.js
takwimu/templates/settings_js.html
takwimu/views.py

Enable same-origin policy for HURUmap & Flourish Viz: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Changing_origin

Enable same-origin for HURUmap & Flourish Viz
