TakwimuAfrica/Takwimu

LICENSE, README.md
Added open source license .
Fixes #6
=> Add Open Source License

takwimu/templates/takwimu/_includes/header/profile.html
=> Implement Topic section buttons

.gitignore, Makefile, README.md, requirements.txt, takwimu/__init__.py, takwimu/app.py, takwimu/settings.py, takwimu/signals.py, takwimu/wagtail_hooks.py
Created Model Pages in Wagtail admin to add new Data, Publishers and Indicators to Takwimu. 
Fixes #112
=> Upload Data Indicators

takwimu/templates/takwimu/about/contact.html
=> Add partner logos section  in contact page

takwimu/models/dashboard.py, takwimu/templates/takwimu/_includes/profile/country_selector.html
Show countries in dropdown
Fixes #127
=> Fixes Country Selector on Profile Section Pages

takwimu/templates/takwimu/_includes/header/profile.html, takwimu/templates/takwimu/_includes/header/toc.html, takwimu/templates/takwimu/_includes/profile/country_selector.html
=> Miscellaneous bug fixes from Steen's review 5/07/18

takwimu/templates/takwimu/_includes/footer.html
Updated the footer to match the new designs
Fixes #146
=> Update footer to new designs

takwimu/templates/takwimu/_includes/sections/updates.html
Update updates section to match new designs
Related #153
=> Update Updates Section

takwimu/templates/takwimu/_layouts/_base.html
Added zendesk. This is the help desk or support feature to allow end-users to ask for assistance with platform navigation, content clarification, or other information.
Fixes #12 
=> Add Zendesk chat

takwimu/templates/takwimu/_includes/navbar/_index.html
Remove data link from the navbar
=> Remove data link in navbar

takwimu/templates/takwimu/_includes/navbar/support_services.html
I have update the support services pages in the CMS as well in my local development. The changes online affect only `Standard service` and `Premium services` while the local changes affect the Help & Support column as well
Fixes #228
=> Update our services

takwimu/templates/takwimu/about/support_services.html
Add small box-shadow 
Fixes #223
=> Add box-shadow in a card

takwimu/templates/takwimu/_includes/navbar/_dropdown.html, takwimu/templates/takwimu/_includes/navbar/about.html
Add box-shadow in a mega dropdown, Quick note: The changes are significantly small to see
Fixes #222
=> Add mega drop shadow

takwimu/templates/takwimu/_includes/navbar/_index.html, takwimu/templates/takwimu/_includes/navbar/support_services.html
Rename services link, add contact us link
Fixes #209
=> Improve navbar design

takwimu/templates/takwimu/_includes/footer.html, takwimu/templates/takwimu/_includes/navbar/about.html
=> Separate gates logo to sponsored by column

takwimu/templates/takwimu/_includes/footer.html, takwimu/templates/takwimu/_includes/navbar/about.html
Change the logo order to africapractice, Code for Africa, iHub
=> Change logo order

takwimu/templates/takwimu/_includes/partners.html
Moved partnership logo.
Fixes #266
**Requested Changes**
=> rearrange logo in partnership section

takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
Reduced `font-size` to avoid line-break when there's more than 10 characters.
Fixes #264
=> Fix title line break

takwimu/templates/takwimu/_includes/sections/support-services/button.html
Improved support services button as directed on issue 213
Fixes #213
=> improve service button styling

takwimu/profiles/census.py, takwimu/sql/registered_accredited_voters.sql, takwimu/sql/valid_invalid_votes.sql, takwimu/sql/votes_per_candidate.sql, takwimu/tables.py, takwimu/templates/profile/profile_detail.html
Added elections data for the 3 countries
=> Add Elections Data

takwimu/templates/takwimu/_includes/navbar/about.html
=> Change instagram icon to medium

README.md, takwimu/templates/takwimu/_includes/footer.html, takwimu/templates/takwimu/_includes/navbar/about.html, takwimu/templates/takwimu/_includes/partners.html
Changed the 'Sponsored by to Supported by`
Fixes #304 
- [ x Bug fix (non-breaking change which fixes an issue)
=> Update reference to bmgf

takwimu/templates/homepage.html, takwimu/templates/profile/profile_detail.html, takwimu/templates/takwimu/_layouts/_base.html
Upgrade font-awesome icons to 5.2
Fixes #295 
=> Upgrade fontawesome to 5.2

takwimu/templates/takwimu/_includes/navbar/_index.html, takwimu/templates/takwimu/_includes/navbar/about.html, takwimu/templates/takwimu/_includes/sections/support-services/button.html, takwimu/templates/takwimu/about/contact.html
Also rename support service to our services
=> Make "About Us" button in navbar clickable

takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #313 
=> Update feedback text

takwimu/templates/takwimu/about/support_services.html
Horizontally align service cards to resemble zeplin design. 
Fixes #265
=> Improve support design cards

takwimu/templates/profile/profile_detail.html, takwimu/templates/takwimu/_includes/sections/explore/countries.html, takwimu/templates/takwimu/profile_page.html
=> Add grayscale in countries

.github/ISSUE_TEMPLATE/data_request.md
Added a GitHub Issue template for Data Requests
Fixes #280
=> Data Request Template

DATA.md
Adding guide for how to respond when replying to Data Requests Community Topic.
=> Updating data guide for data requests

takwimu/profiles/census.py, takwimu/sql/wazimap_geography.sql, takwimu/templates/profile/profile_detail.html, takwimu/templatetags/geotags.py
Displays area of the selected geography
Fixes #354
=> Add Area Size

README.md
Added documentation on how to set up Elasticsearch in development
Fixes #353
=> Add Elasticseach Documentation

takwimu/templates/takwimu/_includes/navbar/support_services.html
Remove community forum link from help and support menu
=> Remove community forum link

takwimu/templates/profile/head2head.html, takwimu/templates/profile/profile_detail.html
Adding comparison for two country profiles.
=> Profile Comparison

takwimu/context_processors.py
Topics should be loaded from *live* pages only.
=> Exclude topics from unpublished pages

takwimu/context_processors.py
Country overview section is added as well as improvements around section
traversal which could cause certain topics to be skipped.
=> Add missing Overview section & improve traversal in Explore by Topic

takwimu/templates/profile/profile_detail.html
Inform the site visitor that charts/statistics are interactive
=> Inform the site visitor charts/statistics are interactive

takwimu/templates/takwimu/_includes/navbar/support_services.html
Changed `github` to `linkedin` in our service tab 
=> [WIP] Add linkedin link in support and service tab

takwimu/models/dashboard.py
Limit the geo choices dropdown to only countries
Fixes #359
=> Geo choices as countries

takwimu/templates/takwimu/_includes/search/table.html
Removed the *Add to collection* button on the search results page,
=> Remove "add to collection" button

takwimu/views.py
'Country Overview' topic was missing from the search results.
=> 'Country Overview' topic was missing from the results

requirements.txt, takwimu/settings.py, takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html, takwimu/urls.py
HURUmap master now uses Wazimap 1.2
=> Update to latest HURUmap

takwimu/templates/takwimu/_includes/navbar/_index.html
Rename **About Us** link to **About** to improve navbar spacing.
=> Rename About Us link to About

takwimu/static/css/takwimu.scss, takwimu/templates/takwimu/_includes/search/_popover.html
Improve on hover action on pagination links, also improve interaction on closable tags on the filter
=> Improve search

takwimu/templates/profile/profile_detail_base.html
JavaScript blocks were included multiple times causing errors to be through in the console, multiple GA tracking to created, etc.
=> Remove duplicated javascript body includes

takwimu/templates/profile/profile_detail_takwimu.html, takwimu/templatetags/geotags.py
Missing Census Year & miss-aligned health charts.
=> [Hotfix] Fixes Census Year & UI

takwimu/templates/takwimu/_includes/profile/topic_detail.html
Style **Show more/less** button to resemble [zeplin](https://zpl.io/a3q5DXW) designs.
Fixes #399
=> Style show more button in profile page

takwimu/templates/takwimu/_includes/dataview/hurumap.html
HURUmap widget `iframe` id was not set properly and hence the included script could not find the necessary viz to render.
=> Fix HURUmap widget iframe id and message handling

takwimu/templates/takwimu/_includes/sections/explore/countries.html
=> Enable Kenya

takwimu/templates/takwimu/_includes/sections/explore/countries.html
Enable Ethiopia in country profiles.
=> Enable ethiopia

takwimu/context_processors.py
Enable South Africa country profile.
=> Enable South Africa

takwimu/context_processors.py, takwimu/utils/medium_models.py
Fix trending stories were not showing
=> Fix Trending Stories

docker-entrypoint.sh
Index using the custom `update_topcs_index` command instead of the wagtail `update_index`.
=> Replace wagtail indexing with custom indexing

takwimu/search/takwimu_search.py
Current custom search configuration does not take into account AWS authentication required to connect to the service. This causes silent errors during indexing and exception at runtime when a site visitor performs a search on the site.
=> [#161743178] Fix elasticsearch aws auth 

takwimu/templates/takwimu/_includes/homepage/hero.html
To improve UX, we should make the carousel auto-play [Finishes
=> Make Homepage Carousel Autoplay [161713298]

takwimu/static/css/takwimu.scss, takwimu/templates/takwimu/_includes/navbar/about.html
Fix Logos on Navbar About Dropdown
=> Fix Logos on Navbar About Dropdown Menu [161713150]

takwimu/templates/takwimu/_layouts/_base.html
Ensure GA with Takwumu ID is created and it's the default.
=> Fix analytics [162576215]

takwimu/templates/takwimu/profile_page.html
Enable:
+ text selection sharing on country profile pages,
+ GA tracking for sharing, and
+ GA tracking for text copied anywhere on the site.
=> Text selection sharing and tracking [162505670]

Dockerfile
Fix missing `hurumap.dashboard`
=> [Hotfix] Upgrade to HURUmap v0.2.8

Dockerfile, takwimu/settings.py
Move all static and media files to S3
=> [#164394873] Move media and Static Files to S3

takwimu/takwimu_ui/src/assets/images/file-paragraph-bg.svg, takwimu/takwimu_ui/src/components/Navigation/CountryAnalysis.js, takwimu/takwimu_ui/src/components/Navigation/DropDownContent.js, takwimu/takwimu_ui/src/components/Navigation/DropDowns.js, takwimu/takwimu_ui/src/components/Navigation/index.js
Created the Country Analysis Dropdown.
=> [Staging] Country Analysis Dropdown

takwimu/settings.py
Remove Topics Context to improve performance
N/A
=> Remove Topics Context

takwimu/models/dashboard.py, takwimu/takwimu_ui/package.json, takwimu/takwimu_ui/public/embed/iframe.html, takwimu/takwimu_ui/public/index.html, takwimu/takwimu_ui/src/Theme.js, takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js, takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfo.js, takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js, takwimu/takwimu_ui/src/components/AnalysisContent/TableOfContent.js, takwimu/takwimu_ui/src/components/AnalysisContent/index.js, takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js, takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js, takwimu/takwimu_ui/src/components/FeaturedData/IFrame.js, takwimu/takwimu_ui/src/components/FeaturedData/index.js, takwimu/takwimu_ui/src/components/Navigation/DropDowns.js, takwimu/takwimu_ui/src/components/Navigation/index.js, takwimu/takwimu_ui/src/components/Next/Analysis.js, takwimu/takwimu_ui/src/components/Next/Card.js, takwimu/takwimu_ui/src/components/Profile/Tabs.js, takwimu/takwimu_ui/src/components/ProfileDetail/index.js, takwimu/takwimu_ui/src/components/RelatedContent/Links.js, takwimu/takwimu_ui/src/components/RelatedContent/index.js, takwimu/takwimu_ui/src/components/ViewCountry/Selection.js, takwimu/takwimu_ui/src/components/ViewCountry/index.js, takwimu/takwimu_ui/src/index.js, takwimu/takwimu_ui/src/pages/AnalysisPage/index.js
Compile various components forming the **Analysis** page(s).
=> [Staging] Compile Analysis page

takwimu/takwimu_ui/public/index.html, takwimu/templates/profile/profile_detail_base.html, takwimu/templates/takwimu/about/index.html, takwimu/templates/takwimu/contact_us_page.html, takwimu/templates/takwimu/home_page.html, takwimu/templates/takwimu/profile_page.html
Ensure each page has a valid `id` i.e. `takwimu.page.id`
N/A
=> [Staging] [Hotfix] Ensure takwimu.page.id

takwimu/takwimu_ui/src/components/Navigation/index.js
Remove shadow in drawer that was introduced in navigation.
Bug:
Fixed:
=> [Staging] Fix remove shadow in drawer

takwimu/takwimu_ui/src/components/AnalysisContent/index.js, takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js, takwimu/takwimu_ui/src/components/FeaturedData/index.js
Fix by checking if widget is null resolves this issue.
=> [Staging] Fix Featured Data not Displaying

takwimu/takwimu_ui/src/components/AnalysisContent/ContentNavigation.js, takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js, takwimu/takwimu_ui/src/components/ContentNavigation.js, takwimu/takwimu_ui/src/components/Faqs/Faq.js, takwimu/takwimu_ui/src/pages/Analysis.js
Allow endpoint to go directly to topic with the topic id as hash on the url.
=> [Staging] Allow url hash to work

takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
Minor fix to not use hard coded media links.
=> [Staging] Minor fix use settings medium link

takwimu/templates/profile/profile_detail_base.html, takwimu/templates/takwimu/_layouts/_base.html
Adds <https://usersnap.com> for UAT.
=> [Staging] Add Usersnap for UAT

takwimu/static/css/takwimu.scss, takwimu/takwimu_ui/src/components/AboutUsContent/index.js, takwimu/takwimu_ui/src/components/LatestNewsStories/StoryCard.js, takwimu/takwimu_ui/src/components/Navigation/DropDownButton.js, takwimu/takwimu_ui/src/components/Next/About.js, takwimu/takwimu_ui/src/components/ProfileDetail/index.js, takwimu/takwimu_ui/src/components/Section.js, takwimu/takwimu_ui/src/components/TableOfContent.js, takwimu/takwimu_ui/src/pages/AboutUs.js
Fix typography on data by topic:
Remove button outline on Data by topic button:
Fix spacing on about us page
Reduce padding on what next card
=> More fixes UI/UX review

takwimu/profiles/census.py, takwimu/settings.py, takwimu/takwimu_ui/src/components/ProfileDetail/index.js
=> [Staging] Profile Charts Comparison

takwimu/takwimu_ui/src/components/DataContainer/DataActions.js, takwimu/takwimu_ui/src/components/DataContainer/EntitiesDataContainer.js, takwimu/takwimu_ui/src/components/DataContainer/HTMLDataContainer.js
Show only available actions for each visuals.
=> [Staging] Enable actionable data actions

takwimu/models/dashboard.py, takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js, takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
- Since data_country field changed, need to update the id.
- Also enforced title so that the saved download will have a name.
=> [Staging] Fix featured data download

takwimu/takwimu_ui/src/components/ProfileDetail/index.js, takwimu/templates/profile/profile_detail_base.html, takwimu/templates/takwimu/_layouts/_base.html, takwimu/templates/takwimu/contact_page.html
=> [Staging] [Hotfix] Contact page & Data by Topic page

takwimu/profiles/census.py, takwimu/takwimu_ui/src/components/Profile/Tabs.js, takwimu/templates/profile/profile_detail_base.html, takwimu/templates/profile/profile_detail_takwimu.html
Categorise WorldBank data into Takwimu categories.
=> [Staging] Categorise WorldBank data

takwimu/templates/profile/profile_detail_base.html, takwimu/templates/takwimu/home_page.html, takwimu/templates/takwimu/profile_page.html
Hotfix staging uses absolute urls and s3.
=> [Staging] Fix Twitter Card Image Endpoints

Dockerfile, takwimu/renderers.py, takwimu/views.py
Flourish viz was throwing errors on staging because media files are stored on s3
=> [Staging] Fix Flourish Viz download

takwimu/renderers.py, takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js, takwimu/views.py
=> [Staging] [Hotfix] Flourish Widget

takwimu/takwimu_ui/src/components/AnalysisContent/topics/CarouselTopic.js
=> [Staging] [Hotfix] carousel topic header

takwimu/takwimu_ui/src/components/ProfileDetail/index.js
=> [FIX] Profile details floater

takwimu/static/js/profile_map_mapit.js, takwimu/takwimu_ui/src/components/ProfileDetail/index.js
Pass pointer events to map below.
Adjust profile detail zIndex to allow map clicking
=> [FIX] Map interaction

takwimu/static/css/embedchart.scss, takwimu/static/css/takwimu.scss, takwimu/static/js/charts.js, takwimu/static/js/profile_map_mapit.js, takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js, takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
Ensure charts have minimum height
=> Ensure charts have minimum height

requirements.txt, takwimu/static/css/embedchart.scss, takwimu/static/css/takwimu.scss, takwimu/static/js/charts.js, takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js, takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
From Wagtail 2.3 [docs](https://docs.wagtail.io/en/v2.3/topics/search/backends.html#elasticsearch-backend):
```
Version 6.3.1 of the Elasticsearch client library is incompatible with Wagtail. Use 6.3.0 or earlier.
```
`v6.3.1` broke `make update_index`
=> [Hotfix] Downgrade elasticsearch client

takwimu/templates/takwimu/_layouts/_base.html
Fix typo on favicon import statement
=> [Hotfix] favicon static import

takwimu/context_processors.py, takwimu/takwimu_ui/.babelrc, takwimu/takwimu_ui/.eslintrc.json, takwimu/takwimu_ui/package.json, takwimu/takwimu_ui/src/components/AnalysisContent/Actions/DownloadPDF.js, takwimu/takwimu_ui/src/components/AnalysisContent/Actions/index.js, takwimu/takwimu_ui/src/components/AnalysisContent/index.js, takwimu/takwimu_ui/src/components/DataContainer/PDFDataContainer.js, takwimu/takwimu_ui/src/modules/pdf.js, takwimu/takwimu_ui/src/modules/react-pdf.js, takwimu/takwimu_ui/yarn.lock, takwimu/templates/takwimu/_layouts/_base.html
We've grown past the recommended single chunk size for our build. This PR introduce code splitting targeting the two largest libraries we're using: `pdf-js` and `react-pdf`.
=> Improve Build

takwimu/takwimu_ui/package.json, takwimu/takwimu_ui/src/index.js, takwimu/takwimu_ui/yarn.lock, takwimu/templates/data/_base_data.html, takwimu/templates/profile/profile_detail_base.html, takwimu/templates/takwimu/_includes/footer.html, takwimu/templates/takwimu/home_page.html
Microsoft Edge does not support some of the features `Create React App` supports by default and hence we need to use at least `polyfill/stable` for it to work properly.
We also fix:
=> [Hotfix] Microsoft Edge support

Dockerfile, takwimu/templates/data/_base_data.html, takwimu/templates/data/data_map.html, takwimu/templates/profile/profile_detail_base.html
Update HURUmap & cleanup templates to fix the following error when running `make compilescss`:
```
Error parsing template /usr/local/lib/python3.7/site-packages/census/templates/data/data_distribution.html: Invalid block tag on line 119: 'get_static_prefix', expected 'endblock'. Did you forget to register or load this tag?
Error parsing template /src/hurumap/hurumap/templates/data/_base_data.html: Invalid block tag on line 119: 'get_static_prefix', expected 'endblock'. Did you forget to register or load this tag?
Invalid template /src/takwimu/takwimu/templates/data/_base_data.html: Invalid block tag on line 119: 'get_static_prefix', expected 'endblock'. Did you forget to register or load this tag?
Error parsing template /src/takwimu/takwimu/templates/data/data_map.html: Invalid block tag …
```
=> Update HURUmap & cleanup templates

takwimu/takwimu_ui/public/index.html, takwimu/takwimu_ui/src/components/Error.js, takwimu/takwimu_ui/src/components/ErrorPage.js, takwimu/takwimu_ui/src/index.js, takwimu/takwimu_ui/src/pages/500.js, takwimu/templates/500.html, takwimu/urls.py, takwimu/views.py
=> Add custom 500 error page

takwimu/takwimu_ui/public/index.html, takwimu/takwimu_ui/src/components/Error.js, takwimu/takwimu_ui/src/components/ErrorPage.js, takwimu/takwimu_ui/src/components/Next/About.js, takwimu/takwimu_ui/src/components/Next/Contact.js, takwimu/takwimu_ui/src/components/SearchInput/Input.js, takwimu/takwimu_ui/src/components/SearchInput/index.js, takwimu/takwimu_ui/src/components/SearchResults/index.js, takwimu/takwimu_ui/src/index.js, takwimu/takwimu_ui/src/pages/404.js, takwimu/takwimu_ui/src/pages/500.js, takwimu/templates/404.html, takwimu/templates/500.html, takwimu/urls.py, takwimu/views.py
=> Add custom 404 error page

takwimu/profiles/census.py, takwimu/static/css/takwimu.scss, takwimu/static/js/charts.js, takwimu/templates/profile/profile_detail_takwimu.html
Replace Population stat list on data by topic page with chart specific data & titles
=> Data by Topic chart stat list

takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js, takwimu/takwimu_ui/src/components/Navigation/DropDownContent.js, takwimu/takwimu_ui/src/components/Navigation/DropDowns.js
=> Fix Navigation Issues

Dockerfile
Upgrade HURUmap to `v0.6.6`
N/A
=> [Chore] Upgrade HURUmap

Dockerfile, takwimu/settings.py
The prepend/append method of adding to `MIDDLEWARE` seems to produce `MIDDLEWARE` that do not follow the recommend order: https://docs.djangoproject.com/en/2.2/ref/middleware/#middleware-ordering
This PR addresses that and ensures `CorsMiddleware` is as high as possible.
=> MIDDLEWARE Fixes

takwimu/templates/profile/profile_detail_base.html
=> Show chart actions on sub-national profile charts

takwimu/takwimu_ui/src/components/Next/Home.js
Switch mailing list address to **Sendinblue**
=> [Hotfix] Switch mailing list address

takwimu/profiles/census.py, takwimu/templates/profile/profile_detail_takwimu.html
Fixes [#169451927](https://www.pivotaltracker.com/story/show/169451927)
=> Fix chart data & Remove suffix percent for total

takwimu/profiles/census.py
Update KNBS data links
~`https://www.knbs.or.ke/download/economic-survey-2018/`~
`https://www.knbs.or.ke/?wpdmpro=economic-survey-2018`
~`https://www.knbs.or.ke/download/statistics-abstract-2018/`~
`https://www.knbs.or.ke/?wpdmpro=statistics-abstract-2018`
=> [Hotfix] Update KNBS data links
